---
title: personalise-me
hero_image: images/banner.png
description: Use Javascript to create interactive websites
version: 4
listed: false
copyedit: false
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: Add HTML for more images into div/ Form elements
- title: Footer (DOM manipulation)/Event Handling/Functions/Logic
- title: Light Mode/Local Storage
- title: Captcha
- title: Reflection
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
- title: Upgrade your project
- title: What next?
