---
title: 漫画人物
hero_image: images/banner.png
description: 创建一个超级英雄设计网站！
version: 4
listed: true
copyedit: false
last_tested: '2021-03-26'
steps:
- title: 介绍
- title: 添加版权文本
- title: 添加表单元素
  completion: engaged
- title: 显示和隐藏元素
- title: 更改摘要
- title: 检查用户输入
- title: 浅色模式主题
- title: 首页轮播图
  completion: internal
- title: 回顾与思考
  completion: external
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
- title: 升级你的项目
